./miner 1 4 skittle > test_threads.txt
./miner 2 4 skittle >> test_threads.txt
./miner 4 4 skittle >> test_threads.txt
./miner 8 4 skittle >> test_threads.txt
./miner 1 8 skittle >> test_threads.txt
./miner 2 8 skittle >> test_threads.txt
./miner 4 8 skittle >> test_threads.txt
./miner 8 8 skittle >> test_threads.txt
./miner 1 12 skittle >> test_threads.txt
./miner 2 12 skittle >> test_threads.txt
./miner 4 12 skittle >> test_threads.txt
./miner 8 12 skittle >> test_threads.txt
./miner 1 16 skittle >> test_threads.txt
./miner 2 16 skittle >> test_threads.txt
./miner 4 16 skittle >> test_threads.txt
./miner 8 16 skittle >> test_threads.txt
./miner 1 20 skittle >> test_threads.txt
./miner 2 20 skittle >> test_threads.txt
./miner 4 20 skittle >> test_threads.txt
./miner 8 20 skittle >> test_threads.txt
./miner 1 24 skittle >> test_threads.txt
./miner 2 24 skittle >> test_threads.txt
./miner 4 24 skittle >> test_threads.txt
./miner 8 24 skittle >> test_threads.txt
./miner 1 28 skittle >> test_threads.txt
./miner 2 28 skittle >> test_threads.txt
./miner 4 28 skittle >> test_threads.txt
./miner 8 28 skittle >> test_threads.txt